name: Github Action Deploy docs
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: install pnpm
      run: npm i pnpm@latest -g
    - name: install dependencies
      run: pnpm install
    - name: Setup Deploy Private Key
      env:
        DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa 
        chmod 600 * ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: setup git config
      run: |
        git config --global user.name "sudongyuer"
        git config --global user.email "976499226@qq.com"
        sh ./deploy.sh
