name: Github Action Deploy docs
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.TOKEN }}
    - name: setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: install pnpm
      run: npm i pnpm@latest -g
    - name: install dependencies
      run: pnpm install
    - name: setup git config
      run: |
        git config --global user.name "sudongyuer"
        git config --global user.email "976499226@qq.com"
        git config --list
        sh ./deploy.sh
